Developed Bubble sort.
rootDEV2990/bubblesort_ruby pull request #1
Opened 2020-04-19 13:31 UTC by rootDEV2990

Please help review my bubble sort in ruby. =)

T.Y.
-Miguel

2020-04-20 03:34 UTC, majovanilla requested changes
Hi @rootDEV2990 

## Good job on this project! 👍


There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- Check the commented code below.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-20 03:34 UTC, majovanilla commented on sortby.rb
> +end
In this line, you are returning true or false beside the sorted array. That shouldn't happen if you integrate both methods.

2020-04-20 03:34 UTC, majovanilla commented on sortby.rb
> +end
What's this method for? You should only have two methods on this project: 
bubble_sort
bubble_sort_by
I recommend you to change the names to match those.
Also, delete the extra method and make sure you have only two that return the sorted array.

2020-04-20 03:34 UTC, majovanilla commented on sortby.rb
> +end
This should be your main method and it should integrate the one on the top. Please make the necessary adjustments.

2020-04-20 03:34 UTC, majovanilla commented on sortby.rb
> +  items_unsorted = true
This method doesn't take a block as an argument and order the elements using the block. Please make the necessary adjustments to fix it. Right now, when you pass a block, it's returning the array sorted but not with the order of the block passed.

2020-04-20 03:34 UTC, majovanilla commented on README.md
> +https://www.ruby-lang.org/en/downloads/
This part is not descriptive of your project. You don't have to use the prerequisites but you should give the user some guidance to run your methods.

2020-04-28 23:51 UTC, rootDEV2990 commented
Rewrote the bubble sort please help review i am still working on fixing rubocop errors

2020-04-29 07:05 UTC, suretrust requested changes
Hi, @rootDEV2990, 👋 

### Great job implementing some of the suggested changes. 🙌 Please see my comments on your code. 👇 

- [x] Let's fix all linter errors.

**Kindly submit for another code review request once these issues have been fixed.** _Happy coding!_ 🎉

2020-04-29 07:05 UTC, suretrust commented on sortby.rb
> +      swap = true
You are missing an `end` here.
```ruby
if (condition)
end
```

2020-04-29 07:05 UTC, suretrust commented on sortby.rb
> +p bubble_sort(input)
Let's remove this once you are done.

2020-04-29 07:05 UTC, suretrust commented on sortby.rb
> +p bubble_sort_by(inp) { |first, second| second - first }
Let's remove this once you are done.

2020-04-29 19:57 UTC, rootDEV2990 commented
hi i fixed rubo cop and added missing ends to my if but i dont know what this means....
![Screen Shot 2020-04-29 at 2 55 40 PM](https://user-images.githubusercontent.com/60228072/80640875-a7b26500-8a29-11ea-8053-f765c4e6d767.png)

2020-04-29 20:34 UTC, pelzolga123 requested changes
The linter file requires changes.

2020-04-29 20:34 UTC, pelzolga123 commented
## Hi Miguel! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
Just one thing left:
* [ ] Make sure your `.rubocop.yml` file has the correct content. You can find original one [here](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml).

### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-30 15:02 UTC, rootDEV2990 commented
Updated rubocop and fixed errors to request approval to merge to master.

2020-04-30 20:04 UTC, Forison approved these changes
## Status:: Approved✔️
## 👋 Miguel 
Good job on addressing the issues raised earlier. Go ahead and merge branch and proceed to the next task
#### Happy coding
Addo

2020-04-30 22:53 UTC, merged